### ISSUE TITLE
ensure worker nodes become available

### ISSUE THREAD

**Issue by errordeveloper** [cilium/openshift-terraform-upi#1]

**Comment by errordeveloper** [comment]
https://docs.openshift.com/container-platform/4.6/installing/installing_aws/installing-aws-user-infra.html#installation-creating-aws-worker_installing-aws-user-infra

**Comment by errordeveloper** [comment]
https://docs.openshift.com/container-platform/4.1/machine_management/creating-machineset.html ...probably preferred

**Comment by errordeveloper** [comment]
Turns out there machines already, just need to debug whatever is going on with these...
```
NAMESPACE               NAME                                   PHASE   TYPE   REGION   ZONE   AGE
openshift-machine-api   test-3-wbqhm-master-0                                                 105m
openshift-machine-api   test-3-wbqhm-master-1                                                 105m
openshift-machine-api   test-3-wbqhm-master-2                                                 105m
openshift-machine-api   test-3-wbqhm-worker-eu-west-1a-xfgbf                                  100m
openshift-machine-api   test-3-wbqhm-worker-eu-west-1b-txswq                                  100m
openshift-machine-api   test-3-wbqhm-worker-eu-west-1c-4rznv                                  100m
```

**Comment by errordeveloper** [comment]
Looks like CCO is failing to talk to IAM:
```
time="2021-02-25T10:27:39Z" level=error msg="error getting user: {\n\n}" actuator=aws cr=openshift-cloud-credential-operator/aws-ebs-csi-driver-operator error="RequestError: send request failed\ncaused by: Post \"https://iam.amazonaws.com/\": dial tcp: i/o timeout"
time="2021-02-25T10:27:39Z" level=error msg="error determining whether a credentials update is needed" actuator=aws cr=openshift-cloud-credential-operator/aws-ebs-csi-driver-operator error="unable to read info for username {\n\n}: RequestError: send request failed\ncaused by: Post \"https://iam.amazonaws.com/\": dial tcp: i/o timeout"
time="2021-02-25T10:27:39Z" level=error msg="error syncing credentials: error determining whether a credentials update is needed" controller=credreq cr=openshift-cloud-credential-operator/aws-ebs-csi-driver-operator secret=openshift-cluster-csi-drivers/ebs-cloud-credentials
time="2021-02-25T10:27:39Z" level=error msg="errored with condition: CredentialsProvisionFailure" controller=credreq cr=openshift-cloud-credential-operator/aws-ebs-csi-driver-operator secret=openshift-cluster-csi-drivers/ebs-cloud-credentials
```

**Comment by errordeveloper** [comment]
Having fixed Cilium ports, I can see this:
```
status:
  errorMessage: 'test-7-bfh9b-worker-eu-west-1a-8l7z8: reconciler failed to Create
    machine: failed to launch instance: error getting subnet IDs: no subnet IDs were
    found'
  lastUpdated: "2021-02-25T18:24:05Z"
  phase: Failed
  providerStatus:
    conditions:
    - lastProbeTime: "2021-02-25T18:23:45Z"
      lastTransitionTime: "2021-02-25T18:23:45Z"
      message: 'error getting subnet IDs: no subnet IDs were found'
      reason: MachineCreationFailed
      status: "False"
      type: MachineCreation
```

The error only shows up in the object, nothing similar is to be found in machine-api-controller logs... It does happen for master machines as well as the workers.
